#!/bin/bash

PHP_VERSION=`echo $SOURCE_BRANCH | sed -r 's/php-(.+)\/deployer-(.+)/\1/'`
DEPLOYER_VERSION=`echo $SOURCE_BRANCH | sed -r 's/php-(.+)\/deployer-(.+)/\2/'`

if [[ $DEPLOYER_VERSION =~ ^[0-9]+(\.[0-9]+)?$ ]] ; then
  DEPLOYER_VERSION=$DEPLOYER_VERSION.*
fi

if [ $SOURCE_BRANCH = "main" ] ; then
  PHP_VERSION=7
  DEPLOYER_VERSION=6.8.0
fi

docker build \
  --build-arg PHP_VERSION=$PHP_VERSION \
  --build-arg DEPLOYER_VERSION=$DEPLOYER_VERSION \
  -f $DOCKERFILE_PATH \
  -t $IMAGE_NAME \
  .
