name: build

# @see https://stackoverflow.com/questions/61891328/trigger-github-action-only-on-new-tags#answer-61892639
on:
  push:
    tags:
      - '**'

jobs:
  # @see https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # @see https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions#answer-58034787
      # @see https://docs.github.com/en/github-ae@latest/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idoutputs
      - name: Get variables from pushed tag
        id: get_variables
        run: |
          PHP_VERSION=`echo ${GITHUB_REF#refs/tags/} | sed -r "s/php-(.+)\/deployer-(.+)/\1/"`
          DEPLOYER_VERSION=`echo ${GITHUB_REF#refs/tags/} | sed -r "s/php-(.+)\/deployer-(.+)/\2/"`
          IMAGE_TAG=$DEPLOYER_VERSION
          
          if [[ $DEPLOYER_VERSION =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
            DEPLOYER_VERSION=$DEPLOYER_VERSION.*
          fi
          
          echo ::set-output name=PHP_VERSION::$PHP_VERSION
          echo ::set-output name=DEPLOYER_VERSION::$DEPLOYER_VERSION
          echo ::set-output name=IMAGE_TAG::$IMAGE_TAG

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            PHP_VERSION=${{ steps.get_variables.outputs.PHP_VERSION }}
            DEPLOYER_VERSION=${{ steps.get_variables.outputs.DEPLOYER_VERSION }}
          tags: |
            ttskch/deployer:${{ steps.get_variables.outputs.IMAGE_TAG }}
            ttskch/deployer:latest
          push: true
